[tool.black]
line-length = 119

[tool.pytest.ini_options]
log_file = "pytest.log"
log_file_level = "WARNING"
log_file_format = "[%(asctime)s] - %(process)08d - %(message)s (%(lineno)03d: %(filename)s)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = [
   "error",
   "ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning",
   "ignore:Deprecated call to `pkg_resources\\.declare_namespace\\('google.*'\\):DeprecationWarning",
   "ignore:pkg_resources is deprecated as an API:DeprecationWarning"
 ]
 